### ISSUE TITLE
gogs 0.7.33 fails to start

### ISSUE THREAD

**Issue by kernel164** [gogits/gogs#2115]
It was working fine with gogs v0.7.22

we use init script - scripts/init/centos/gogs

content of /etc/sysconfig/gogs
```
NAME=gogs
GOGS_HOME=/opt/gogs
GOGS_PATH=${GOGS_HOME}/$NAME
GOGS_USER=git
SERVICENAME="gogs"
LOCKFILE=/var/lock/subsys/gogs
LOGPATH=/var/log/gogs
LOGFILE=${LOGPATH}/gogs.log
RETVAL=0
export USERNAME=git
export GOGS_CUSTOM=/opt/gogs-data
```
note: LOGPATH is /var/log/logs

now `service gogs start` fails...

content of /var/log/gogs/gogs.log
```
2015/12/07 10:11:25 ^[[1;36m[T] Custom path: /opt/gogs-data^[[0m
2015/12/07 10:11:25 ^[[1;36m[T] Log path: /opt/gogs/log^[[0m
2015/12/07 10:11:25 ^[[1;32m[I] GOGS 0.7.33.1205 Beta^[[0m
2015/12/07 10:11:25 ^[[1;31m[...s/modules/log/log.go:298 Error()] [E] Fail to set logger(file): open /opt/gogs/log/gogs.log: no such file or directory^[[0m
```

**Comment by andreynering** [comment]
Same issue here on Windows.

[Log file](https://gist.githubusercontent.com/andreynering/d291e0c4c25944fbb640/raw/93ce0947f92503f561596745a25820a1062bfd36/gogs.log).

**Comment by kenno** [comment]
I can't start gogs either. I have a similar issue with andreynering. I'm using PostgreSQL. Gogs is compiled with Go 1.5.1 and 1.5.2.
[gogs_log_0.7.33.txt](https://github.com/gogits/gogs/files/53930/gogs_log_0.7.33.txt)

**Comment by Unknwon** [comment]
Are you guys using redid?

**Comment by jbub** [comment]
same here, Go 1.5.2, Postgres, Redis

**Comment by andreynering** [comment]
> Are you guys using redis?

Yes.

**Comment by Unknwon** [comment]
@andreynering have you updated all deps and how's your config for cache looks like?

**Comment by Unknwon** [comment]
@kernel164 what if you create `/opt/gogs/log/` first?

**Comment by andreynering** [comment]
> Have you updated all deps?

I'm not compiling from source. I downloaded [the uploaded version](https://github.com/gogits/gogs/releases/tag/v0.7.33).

> How's your config for cache looks like?

I was using Redis for cache and session. Now I changed both to "memory" and Gogs is working again.

**Comment by Unknwon** [comment]
@andreynering I tested `network=tcp,addr=:6379,db=0,pool_size=100,idle_timeout=180` but does not seem to panic...

**Comment by Unknwon** [comment]
OK I can reproduce it by `network=tcp,addr=:6379,db=0,pool_size=100,idle_timeout=` which is not correct config BTW.

Not sure if it's the same case as yours?

**Comment by andreynering** [comment]
I was using `network=tcp,addr=localhost:6379,password=,db=0,pool_size=100,idle_timeout=180`.

It works for the previous version.

**Comment by Unknwon** [comment]
> network=tcp,addr=localhost:6379,password=,db=0,pool_size=100,idle_timeout=180

Does not panic either... hmm...

**Comment by jbub** [comment]
Im using `network=tcp,addr=127.0.0.1:6379,db=4,pool_size=100,idle_timeout=180` for session and `network=tcp,addr=127.0.0.1:6379,db=3,pool_size=100,idle_timeout=180` for cache if that helps.

**Comment by Unknwon** [comment]
@jbub thanks! But looks no real difference from mine one, strange.

**Comment by jbub** [comment]
Here are the Git hashes of repos which my binary was built against:
- github.com/gogits/gogs b5f6206a659eaa76382774675f2e3f2664d0f501
- github.com/go-macaron/session 66031fcb37a0fff002a1f028eb0b3a815c78306b
- github.com/go-macaron/cache 56173531277692bc2925924d51fda1cd0a6b8178
- gopkg.in/redis.v2 e6179049628164864e6e84e973cfb56335748dea

**Comment by Unknwon** [comment]
@jbub please do `go get -u gopkg.in/ini.v1` and recompile Gogs.

**Comment by jbub** [comment]
@Unknwon Back in business! Thank you!

**Comment by Unknwon** [comment]
👍🏻

**Comment by kenno** [comment]
I use redis too. Unfortunately, won't be able to test it until I get off work today. I'm pretty sure it'll work again though!

**Comment by kernel164** [comment]
I created `/opt/gogs/log/` folder. 
`service gogs start` works but fails when page is loaded

```
[Macaron] Started GET / for 86.117.179.151
[Macaron] PANIC: session(start): mkdir data: permission denied
/usr/local/go/src/runtime/panic.go:423 (0x4c2089)
/home/vagrant/go/src/github.com/go-macaron/session/session.go:156 (0x7be5d7)
/usr/local/go/src/runtime/asm_amd64.s:437 (0x4f32de)
/usr/local/go/src/reflect/value.go:432 (0x98942a)
/usr/local/go/src/reflect/value.go:300 (0x9880f1)
/home/vagrant/go/src/github.com/go-macaron/inject/inject.go:117 (0xbd24e2)
/home/vagrant/go/src/gopkg.in/macaron.v1/context.go:113 (0x86f3e7)
/home/vagrant/go/src/gopkg.in/macaron.v1/context.go:104 (0x86f2cc)
/home/vagrant/go/src/github.com/go-macaron/gzip/gzip.go:93 (0x7b437a)
/usr/local/go/src/runtime/asm_amd64.s:437 (0x4f32de)
/usr/local/go/src/reflect/value.go:432 (0x98942a)
/usr/local/go/src/reflect/value.go:300 (0x9880f1)
/home/vagrant/go/src/github.com/go-macaron/inject/inject.go:117 (0xbd24e2)
/home/vagrant/go/src/gopkg.in/macaron.v1/context.go:113 (0x86f3e7)
/home/vagrant/go/src/gopkg.in/macaron.v1/context.go:104 (0x86f2cc)
/home/vagrant/go/src/gopkg.in/macaron.v1/recovery.go:161 (0x884752)
/usr/local/go/src/runtime/asm_amd64.s:437 (0x4f32de)
/usr/local/go/src/reflect/value.go:432 (0x98942a)
/usr/local/go/src/reflect/value.go:300 (0x9880f1)
/home/vagrant/go/src/github.com/go-macaron/inject/inject.go:117 (0xbd24e2)
/home/vagrant/go/src/gopkg.in/macaron.v1/context.go:113 (0x86f3e7)
/home/vagrant/go/src/gopkg.in/macaron.v1/context.go:104 (0x86f2cc)
/home/vagrant/go/src/gopkg.in/macaron.v1/logger.go:40 (0x88339e)
/usr/local/go/src/runtime/asm_amd64.s:437 (0x4f32de)
/usr/local/go/src/reflect/value.go:432 (0x98942a)
/usr/local/go/src/reflect/value.go:300 (0x9880f1)
/home/vagrant/go/src/github.com/go-macaron/inject/inject.go:117 (0xbd24e2)
/home/vagrant/go/src/gopkg.in/macaron.v1/context.go:113 (0x86f3e7)
/home/vagrant/go/src/gopkg.in/macaron.v1/router.go:184 (0x885ec4)
/home/vagrant/go/src/gopkg.in/macaron.v1/router.go:286 (0x87c84d)
/home/vagrant/go/src/gopkg.in/macaron.v1/macaron.go:175 (0x87478a)
/usr/local/go/src/net/http/server.go:1862 (0x77678e)
/usr/local/go/src/net/http/server.go:1361 (0x773f7e)
/usr/local/go/src/runtime/asm_amd64.s:1696 (0x4f5621)
2015/12/08 05:54:15 http: multiple response.WriteHeader calls
[Macaron] Completed / 500 Internal Server Error in 2.786453ms

```

then I created /opt/gogs/data folder. now it works.

**Comment by Unknwon** [comment]
Looks like `/opt/gogs/log/` can't be created automatically because of same `permission issue` as your `data` directory.

**Comment by Unknwon** [comment]
Pushed a fix for more precise error message, the current one (`no such file or directory`) is indeed very confusing.

**Comment by kernel164** [comment]
It was working fine with v0.7.22
Issue: I use custom data, log location. v0.7.33 is trying to create data, log dir at default location.
content of /etc/sysconfig/gogs -> `GOGS_CUSTOM=/opt/gogs-data`, `LOGPATH=/var/log/gogs`
```
NAME=gogs
GOGS_HOME=/opt/gogs
GOGS_PATH=${GOGS_HOME}/$NAME
GOGS_USER=git
SERVICENAME="gogs"
LOCKFILE=/var/lock/subsys/gogs
LOGPATH=/var/log/gogs
LOGFILE=${LOGPATH}/gogs.log
RETVAL=0
export USERNAME=git
export GOGS_CUSTOM=/opt/gogs-data
```

partial content of my /opt/gogs-data/conf/app.ini
I use ` /opt/gogs-data/db` for DB and `/data/git/gogs/repos` for repos.
```
[database]
DB_TYPE = sqlite3
PATH = /opt/gogs-data/db/gogs.db

[repository]
ROOT = /data/git/gogs/repos
```

**Comment by Unknwon** [comment]
Just note that `LOGPATH` does not affect Gogs's log path.

**Comment by kenno** [comment]
Good news, I got Gogs running again!
As suggested, I did:  $ go get -u gopkg.in/ini.v1 before building Gogs.

One question, how do we know if we need to update any sub-modules (not sure if that's what it's called.)? This is my first timing having to update this sub-module when updating Gogs.

Thanks.

**Comment by Unknwon** [comment]
@kenno normally you will get a compile error.

In other cases, Gogs has [version checker](https://github.com/gogits/gogs/blob/master/cmd/web.go#L79-L88).

But this bug was not detected, so none of them helped.

**Comment by Unknwon** [comment]
Close for now, but open for continuing discussion.
